### ISSUE TITLE
Sggestion of New Things That Could Be Added

### ISSUE THREAD

**Issue by roger2115** [DereWah/FireModes#1]
# Suggestion of New Things That Could Be Added:
- **Maybe you could add options in Config to Disable the ammo counter and preview of your current weapon firing mode.**
- **Maybe you could add options in Config to Translate "Firing Mode", "Burst" etc.**

**Comment by DereWah** [comment]
Just updated: [f195f66](https://github.com/DereWah/FireModes/commit/f195f665a29d0de17f05080b982377df6240710b)
